### PR TITLE
Fix/config validation conditional

### PR DESCRIPTION
**Pull request by sagold**
Hi @hjerling.

The cli app aborts for a missing `cert` option in config. This commit adds an additional check for this case.

Regards,
sagold

### CODE REVIEW

**Comment by hjerling** [comment]
Hi @sagold,

Thanks for your contribution. I'll try and have a look at your suggested changes as soon as possible.

I believe this PR contains the commits for both PR #2 and #3? Is that intentional? It might be obvious when I get a chance to look at them properly, but it was something I spotted initially. 

Thanks,
Johan

**Comment by sagold** [comment]
Hi @hjerling. Yes indeed. That was not what i had in mind. I'll try fix this :)

**Comment by sagold** [comment]
The feature has been removed from this PR.

**Comment by hjerling** [comment]
Hello @sagold,

Sorry it has taken me this long to look into this PR. Bad timing I'm afraid. 

Can you please explain to me why you would need this? As far as I see it `path.extname()` will always return a `string` to compare with.
This is the output from the node REPL:
```
$ node
> var path = require('path');
undefined
> path.extname('index.html');
'.html'
> path.extname(undefined);
''
> path.extname(null);
''
``` 

This means that even when `options.cert` is `null` or `undefined` the existing logic yields the same result as your PR.

**Comment by sagold** [comment]
Hi hjerling.

I am currently using node `v6.9.1` which might have had an api change to `path.extname`. This is the current output:

```
> path.extname()
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
```

Update: The [docs](https://nodejs.org/api/path.html#path_path_extname_path) refer to this:
> A TypeError is thrown if path is not a string.

**Pull request closed without merging**
